language: node

os: linux

services:
  - docker
  - docker-compose

before_install:
  - echo "Testing udagram"
  - docker compose -f docker-compose-build.yaml build --parallel

script:
  - echo "--Script:"
  - docker ps -a

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker compose push


