apiVersion: v1
kind: Secret
metadata:
  name: test-secret # Name of the secret
  namespace: default # Namespace of the secret
data:
### Alternative data keys are:
  accessKeyId: "YXdzX2FjY2Vzc19rZXlfaWQgPSBBS0lBNk5PU0hGWVRSVFoyRExINwphd3Nfc2VjcmV0X2FjY2Vz"
  secretAccessKey: "c19rZXkgPSBxWmtQK3crT1lQWmM4V21jeDJiTnRkaUc2b24rcS8yRmQyblMvOWtkCg=="
type: Opaque
