apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: udagram-api-user
        image: valentinishimwe/udagram-api-user
        env:
        - name: POSTGRES_USERNAME
          value: postgres_user
        - name: POSTGRES_PASSWORD
          value: postpassword
        - name: POSTGRES_HOST
          value: udagram-database.c4rt8dbpi6rq.us-east-1.rds.amazonaws.com
        - name: POSTGRES_DB
          value: postgres
        - name: AWS_BUCKET
          value: arn:aws:s3:::udagram-bucket-990967705127
        - name: AWS_REGION
          value: us-east-1
        - name: AWS_PROFILE
          value: microuser
        - name: JWT_SECRET
          value: testing
        - name: URL
          value: http://localhost:8100

        ports:
        - containerPort: 80
