apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: valentinishimwe/udagram-api-feed
        envFrom:
        - secretRef:
            name: aws-secret
        - secretRef: 
            name: env-secret
        - configMapRef:
            name: env-configmap
        ports:
        - containerPort: 80

