apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    run: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      run: backend-feed
  template:
    metadata:
      labels:
        run: backend-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: valentinishimwe/udagram-api-feed
        envFrom:
        - secretRef:
            name: aws-secret
        - secretRef: 
            name: env-secret
        - configMapRef:
            name: env-configmap
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 50m
          requests:
            cpu: 10m
