apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: udagram-api-user
        image: valentinishimwe/udagram-api-user
        envFrom:
        - secretRef:
          name: env-secret
        - secretRef:
          name: aws-secret
        - configMapRef:
          name: env-configmap
        ports:
        - containerPort: 80
