apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy
  labels:
    run: reverse-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      run: reverse-proxy
  template:
    metadata:
      labels:
        run: reverse-proxy
    spec:
      containers:
      - name: reverseproxy
        image: valentinishimwe/reverseproxy
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
